name: Build

on:
    push:
        branches: ["main"]

    workflow_dispatch:

env:
    version: ${{ git describe --tags }}

jobs:
    build:
        runs-on: [self-hosted, windows, x64]
        env:
            project: ${{ env.GITHUB_WORKSPACE }}\Supremacy.uproject
            build_dir: ${{ env.GITHUB_WORKSPACE }}\Build
            ConfigFile: ${{ env.GITHUB_WORKSPACE }}\Build\Windows\Supremacy\Saved\Config\Windows\Engine.ini
            DefaultEngine: ${{ env.GITHUB_WORKSPACE }}\Config\DefaultEngine.ini

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: "0"
                  lfs: true

            - name: V8 library check
              id: library
              run: Write-Output "::set-output name=exists::$(Test-Path -Path '${{ env.GITHUB_WOKRSPACE }}\Plugins\UnrealJs\ThirdParty\v8\lib\Win64\Release\v8_init.lib')"

            - name: Install V8 library if not exists
              if: steps.library.outputs.exists == "False"
              run: |
                  Write-Output "V8 library required for UnrealJS is missing, will download/unpack now"
                  Push-Location ${{ env.GITHUB_WOKSPACE }}\Plugins\UnrealJS
                  sh "install-v8-libs.sh"
                  Pop-Location

            - name: Prebuild - set config
              run: |
                  Start-Process -FilePath ${{ env.GITHUB_WORKSPACE }}\Config\inline -ArgumentList "$env:DefaultEngineFile [/Script/Engine.RendererSettings] r.Nanite.RequireDX12=0" -Wait
                  Start-Process -FilePath ${{ env.GITHUB_WORKSPACE }}\Config\inline -ArgumnetList "$env:DefaultEngineFile [/Script/WindowsTargetPlatform.WindowsTargetSettings] DefaultGraphicsRHI=DefaultGraphicsRHI_DX11" -Wait

            - name: Build cook run
              run: Start-Process -FilePath $env:RunUAT -ArgumentList "BuildCookRun -project='$env:project' -targetplatform=Win64 -clientconfig=Development -cook -build -stage -pak -archive -archivedirectory='$env:build_dir'" -Wait

            - name: Post build - set config
              run: |
                  Start-Process -FilePath ${{ env.GITHUB_WORKSPACE }}\Config\inline -ArgumentList "$env:ConfigFile [/Script/Engine.RendererSettings] r.Nanite.RequireDX12=0" -Wait
                  Start-Process -FilePath ${{ env.GITHUB_WORKSPACE }}\Config\inline -ArgumnetList "$env:ConfigFile [/Script/WindowsTargetPlatform.WindowsTargetSettings] DefaultGraphicsRHI=DefaultGraphicsRHI_DX11" -Wait
                  Start-Process -FilePath ${{ env.GITHUB_WORKSPACE }}\Config\inline -ArgurmentList "[/Script/Engine.RendererSettings] r.Nanite.RequireDX12=" -Wait
                  Start-Process -FilePath ${{ env.GITHUB_WORKSPACE }}\Config\inline -ArgumentList "[/Script/WindowsTargetPlatform.WindowsTargetSettings] DefaultGraphicsRHI=DefaultGraphicsRHI_DX12" -Wait
                  Start-Process -FilePath ${{ env.GITHUB_WORKSPACE }}\Config\inline -ArgumentList "$env:ConfigFile [/Game/UI/HUD.HUD_C] Version=$env:version" -Wait
                  Start-Process -FilePath ${{ env.GITHUB_WORKSPACE }}\Config\inline -ArgumentList "$env:ConfigFile [/Game/UI/HUD.HUD_C] BuildBranch=$env:branch" -Wait
                  Start-Process -FilePath ${{ env.GITHUB_WORKSPACE }}\Config\inline -ArgumentList "$env:ConfigFile [/Game/UI/HUD.HUD_C] Hash=${{ env.GIHUB_SHA }}" -Wait
                  Write-Host BuildNo $env:version  Branch $env:branch Hash ${{ env.GIHUB_SHA }}
